AccumulatedAnnualDemand:
    indices: [REGION,COMMODITY,YEAR]
    type: param
    dtype: float
    default: 0
AnnualEmissionLimit:
    indices: [REGION,EMISSION,YEAR]
    type: param
    dtype: float
    default: 99999999
AnnualExogenousEmission:
    indices: [REGION,EMISSION,YEAR]
    type: param
    dtype: float
    default: 0
AvailabilityFactor:
    indices: [REGION,TECHNOLOGY,YEAR]
    type: param
    dtype: float
    default: 1
CapacityFactor:
    indices: [REGION,TECHNOLOGY,TIMESLICE,YEAR]
    type: param
    dtype: float
    default: 1
CapacityOfOneTechnologyUnit:
    indices: [REGION,TECHNOLOGY,YEAR]
    type: param
    dtype: float
    default: 0
CapacityToActivityUnit:
    indices: [REGION,TECHNOLOGY]
    type: param
    dtype: float
    default: 1
CapitalCost:
    indices: [REGION,TECHNOLOGY,YEAR]
    type: param
    dtype: float
    default: 0
# CapitalCostStorage:
#     indices: [REGION,STORAGE,YEAR]
#     type: param
#     dtype: float
#     default: 0
#Conversionld:
#    indices: [TIMESLICE,DAYTYPE]
#    type: param
#    dtype: float
#    default: 0
#Conversionlh:
#    indices: [TIMESLICE,DAILYTIMEBRACKET]
#    type: param
#    dtype: float
#    default: 0
#Conversionls:
#    indices: [TIMESLICE,SEASON]
#    type: paramS
#    dtype: float
#    default: 0
#DAILYTIMEBRACKET:
#    dtype: int
#    type: set
#DaysInDayType:
#    indices: [SEASON,DAYTYPE,YEAR]
#    type: param
#    dtype: float
#    default: 7
#DaySplit:
#    indices: [DAILYTIMEBRACKET,YEAR]
#    type: param
#    dtype: float
#    default: 0.00137
#DAYTYPE:
#    dtype: int
#    type: set
#DepreciationMethod:
#    indices: [REGION]
#    type: param
#    dtype: float
#    default: 1
DiscountRate:
    indices: [REGION]
    type: param
    dtype: float
    default: 0.05
#DiscountRateStorage:
#    indices: [REGION,STORAGE]
#    type: param
#    dtype: float
#    default: 0.05
EMISSION:
    dtype: str
    type: set
EmissionActivityRatio:
    indices: [REGION,TECHNOLOGY,EMISSION,MODE_OF_OPERATION,YEAR]
    type: param
    dtype: float
    default: 0
EmissionsPenalty:
    indices: [REGION,EMISSION,YEAR]
    type: param
    dtype: float
    default: 0
FixedCost:
    indices: [REGION,TECHNOLOGY,YEAR]
    type: param
    dtype: float
    default: 0
COMMODITY:
    dtype: str
    type: set
InputActivityRatio:
    indices: [REGION,TECHNOLOGY,COMMODITY,MODE_OF_OPERATION,YEAR]
    type: param
    dtype: float
    default: 0
#MinStorageCharge:
#    indices: [REGION,STORAGE,YEAR]
#    type: param
#    dtype: float
#    default: 0
MODE_OF_OPERATION:
    dtype: int
    type: set
ModelPeriodEmissionLimit:
    indices: [REGION,EMISSION]
    type: param
    dtype: float
    default: 999999999
ModelPeriodExogenousEmission:
    indices: [REGION,EMISSION]
    type: param
    dtype: float
    default: 0
OperationalLife:
    indices: [REGION,TECHNOLOGY]
    type: param
    dtype: float
    default: 1
# OperationalLifeStorage:
#     indices: [REGION,STORAGE]
#     type: param
#     dtype: float
#     default: 0
OutputActivityRatio:
    indices: [REGION,TECHNOLOGY,COMMODITY,MODE_OF_OPERATION,YEAR]
    type: param
    dtype: float
    default: 0
REGION:
    dtype: str
    type: set
REMinProductionTarget:
    indices: [REGION,YEAR]
    type: param
    dtype: float
    default: 0
ReserveMargin:
    indices: [REGION,YEAR]
    type: param
    dtype: float
    default: 1
ReserveMarginTagFuel:
    indices: [REGION,COMMODITY,YEAR]
    type: param
    dtype: float
    default: 0
ReserveMarginTagTechnology:
    indices: [REGION,TECHNOLOGY,YEAR]
    type: param
    dtype: float
    default: 0
ResidualCapacity:
    indices: [REGION,TECHNOLOGY,YEAR]
    type: param
    dtype: float
    default: 0
#ResidualStorageCapacity:
#    indices: [REGION,STORAGE,YEAR]
#    type: param
#    dtype: float
#    default: 999
RETagTechnology:
    indices: [REGION,TECHNOLOGY,YEAR]
    type: param
    dtype: float
    default: 0
#SEASON:
#    dtype: int
#    type: set
SpecifiedAnnualDemand:
    indices: [REGION,COMMODITY,YEAR]
    type: param
    dtype: float
    default: 0
SpecifiedDemandProfile:
    indices: [REGION,COMMODITY,TIMESLICE,YEAR]
    type: param
    dtype: float
    default: 0
STORAGE:
    dtype: str
    type: set
#StorageLevelStart:
#    indices: [REGION,STORAGE]
#    type: param
#    dtype: float
#    default: 0
#StorageMaxChargeRate:
#    indices: [REGION,STORAGE]
#    type: param
#    dtype: float
#    default: 0
#StorageMaxDischargeRate:
#    indices: [REGION,STORAGE]
#    type: param
#    dtype: float
#    default: 0
TECHNOLOGY:
    dtype: str
    type: set
#TechnologyFromStorage:
#    indices: [REGION,TECHNOLOGY,STORAGE,MODE_OF_OPERATION]
#    type: param
#    dtype: float
#    default: 0
#TechnologyToStorage:
#    indices: [REGION,TECHNOLOGY,STORAGE,MODE_OF_OPERATION]
#    type: param
#    dtype: float
#    default: 0
TIMESLICE:
    dtype: str
    type: set
TotalAnnualMaxCapacity:
    indices: [REGION,TECHNOLOGY,YEAR]
    type: param
    dtype: float
    default: 999999
TotalAnnualMaxCapacityInvestment:
    short_name: TotalAnnualMaxCapacityInvestmen
    indices: [REGION,TECHNOLOGY,YEAR]
    type: param
    dtype: float
    default: 999999
TotalAnnualMinCapacity:
    indices: [REGION,TECHNOLOGY,YEAR]
    type: param
    dtype: float
    default: 0
TotalAnnualMinCapacityInvestment:
    short_name: TotalAnnualMinCapacityInvestmen
    indices: [REGION,TECHNOLOGY,YEAR]
    type: param
    dtype: float
    default: 0
TradeRoute:
    indices: [REGION,COMMODITY,YEAR]
    type: param
    dtype: float
    default: 0
VariableCost:
    indices: [REGION,TECHNOLOGY,MODE_OF_OPERATION,YEAR]
    type: param
    dtype: float
    default: 0
YEAR:
    dtype: int
    type: set
YearSplit:
    indices: [TIMESLICE,YEAR]
    type: param
    dtype: float
    default: 0

TotalTechnologyModelPeriodActivityLowerLimit:
    short_name: TotalTechnologyPeriodActivityLo
    indices: [REGION,TECHNOLOGY]
    type: param
    dtype: float
    default: 0
TotalTechnologyModelPeriodActivityUpperLimit:
    short_name: TotalTechnologyPeriodActivityUp
    indices: [REGION,TECHNOLOGY]
    type: param
    dtype: float
    default: 99999999

TotalTechnologyAnnualActivityLowerLimit:
    short_name: TotalTechnologyAnnualActivityLo
    indices: [REGION,TECHNOLOGY,YEAR]
    type: param
    dtype: float
    default: 0
TotalTechnologyAnnualActivityUpperLimit:
    short_name: TotalTechnologyAnnualActivityUp
    indices: [REGION,TECHNOLOGY,YEAR]
    type: param
    dtype: float
    default: 999999
TechnologyActivityByModeUpperLimit:
    short_name: TechnologyActivityByModeUpperLi
    indices: [REGION,TECHNOLOGY,MODE_OF_OPERATION,YEAR]
    type: param
    dtype: float
    default: 999999
TechnologyActivityByModeLowerLimit:
    short_name: TechnologyActivityByModeLowerLi
    indices: [REGION,TECHNOLOGY,MODE_OF_OPERATION,YEAR]
    type: param
    dtype: float
    default: 0
TechnologyActivityDecreaseByModeLimit:
    short_name: TechnologyActivityDecreaseByMod
    indices: [REGION,TECHNOLOGY,MODE_OF_OPERATION,YEAR]
    type: param
    dtype: float
    default: 0
TechnologyActivityIncreaseByModeLimit:
    short_name: TechnologyActivityIncreaseByMod
    indices: [REGION,TECHNOLOGY,MODE_OF_OPERATION,YEAR]
    type: param
    dtype: float
    default: 0
RETagFuel:
    indices: [REGION,COMMODITY,YEAR]
    type: param
    dtype: float
    default: 0
# UDC:
#     type: set
#     dtype: str
# UDCTag:
#     indices: [REGION,UDC]
#     type: param
#     dtype: float
#     default: -1 
# UDCConstant:
#     indices: [REGION,UDC,YEAR]
#     type: param
#     dtype: float
#     default: 0 
# UDCMultiplierActivity:
#     indices: [REGION,TECHNOLOGY,UDC,YEAR]
#     type: param
#     dtype: float
#     default: 0 
# UDCMultiplierNewCapacity:
#     indices: [REGION,TECHNOLOGY,UDC,YEAR]
#     type: param
#     dtype: float
#     default: 0 
# UDCMultiplierTotalCapacity:
#     indices: [REGION,TECHNOLOGY,UDC,YEAR]
#     type: param
#     dtype: float
#     default: 0 
# InputToNewCapacityRatio:
#     indices: [REGION,TECHNOLOGY,COMMODITY,YEAR]
#     type: param
#     dtype: float
#     default: 0 
# InputToTotalCapacityRatio:
#     indices: [REGION,TECHNOLOGY,COMMODITY,YEAR]
#     type: param
#     dtype: float
#     default: 0 
RateOfActivity:
    indices: [REGION,TIMESLICE,TECHNOLOGY,MODE_OF_OPERATION,YEAR]
    type: result
    dtype: float
    default: 0
AnnualEmissions:
    indices: [REGION,EMISSION,YEAR]
    type: result
    dtype: float
    default: 0
Demand:
    indices: [REGION,TIMESLICE,COMMODITY,YEAR]
    type: result
    dtype: float
    default: 0
NewCapacity:
    indices: [REGION,TECHNOLOGY,YEAR]
    type: result
    dtype: float
    default: 0
TotalCapacityAnnual:
    indices: [REGION,TECHNOLOGY,YEAR]
    type: result
    dtype: float
    default: 0
ft_affiliation:
    indices: [REGION]
    type: param
    dtype: str
    default: ""
ft_scale:
    indices: [REGION]
    type: param
    dtype: int
    default: 0
ft_param_agg:
    indices: [PARAM]
    type: param
    dtype: str
    default: "eq"
ft_param_disagg:
    indices: [PARAM]
    type: param
    dtype: str
    default: "eq"
